### ISSUE TITLE
Cover art not appearing

### ISSUE THREAD

**Issue by Jonasdj95** [doctorfree/Obsidian-Custom-Discogs#2]
I've managed to set up so that it creates the releases in obsidian but there is no cover art. The album covers folder in assets is empty as well. Am I missing something?

**Comment by doctorfree** [comment]
Cover art is downloaded with `wget`. Verify that `wget` is installed on your system and in your execution `PATH`.

In the bash and zsh shells you can check if `wget` is in your `PATH` with the command `type wget`.

If `wget` is installed and in your `PATH` then I will dig further.

**Comment by doctorfree** [comment]
@Hejjeghedderfuglekigger  after verifying that `wget` is installed and in your `PATH`, download and setup the latest release of `Obsidian-Custom-Discogs` at https://github.com/doctorfree/Obsidian-Custom-Discogs/archive/refs/tags/v1.0.2r5.tar.gz

This new release fixes some bugs in the setup process. I was not able to replicate your issue with cover art downloads missing but these fixes may improve your experience. After downloading the release archive, extract it and run the `Setup` script following the setup instructions in the README. Let me know how it goes.

**Comment by doctorfree** [comment]
@Hejjeghedderfuglekigger I have discovered another issue and will be updating with a new release as soon as I fix and test these changes. I would recommend holding off until I publish the `1.0.2r6` release, hopefully this week.

**Comment by Jonasdj95** [comment]
> @Hejjeghedderfuglekigger I have discovered another issue and will be updating with a new release as soon as I fix and test these changes. I would recommend holding off until I publish the `1.0.2r6` release, hopefully this week.

I've tried to do it from scratch. 

in advance please pardon my lack of knowledge of the coding aspects

# process

- mpprc is as instructed
- wget is installed (was before as well)
- I run the setup script 
- the script is running and md files appear in obsidian
- the console in obsidian gives me these error messages for what seems to be each release (don't know if this is relevant)

ExcaliBrain URLParser: Failed to read file Tools/Discogs/Satchmo-_A_Musical_Autobiography_Of_Louis_Armstrong_1928-_Early_1930.md Error: ENOENT: no such file or directory, open '/Users/redacted/Documents/Obsidian-Custom-Discogs-1.0.2r5/Tools/Discogs/Satchmo-_A_Musical_Autobiography_Of_Louis_Armstrong_1928-_Early_1930.md'
app.js:1 

Error: ENOENT: no such file or directory, open '/Users/redacted/Documents/Obsidian-Custom-Discogs-1.0.2r5/Tools/Discogs/Satchmo-_A_Musical_Autobiography_Of_Louis_Armstrong_1928-_Early_1930.md'

- still no cover images
- (might be irrelevant) the folder that should be named from my username is named '-t'
- I'm not sure if if will download the images as a separate process after creating the text-files, so I am waiting for the script to finish running.

# Next step if cover art still doesn't appear

- I will double check if I filled in the token part of mpprc correctly once the setup script finishes.

# Thank you
also thank you so much for being very swift in response and kind

**Comment by doctorfree** [comment]
@Hejjeghedderfuglekigger it was an easy fix and my testing thus far here indicates it is working now. I created a new release, `v1.0.2r6`, that you can download and try. Sorry for the aggravation and thanks for bringing this to my attention.

Let me know if 1.0.2r6 works for you. I do not know why you were getting errors with one particular album previously. If that persists we can look into it.

**Comment by Jonasdj95** [comment]
It is still not working in regards to the cover art appearing. Here is a description of the process. I have tried several times and I've tried my best to be thorough and precise. Thank you

# Devices I've tested on
M1 Macbook pro 
Huawei Matebook running Pop Os (Linux)

# What I've done

- Run `type wget` , `type jq` og `type curl` to verify if these are in fact installed (They were)
- Check homebrew (Mac) if all packages are up to date
- make file @ `$HOME/.config/` named `mpprc` (no file type)
	- File contains below text with my own information

```
The Discogs username can be found by visiting discogs.com. Login, use the

# dropdown of your user icon in the upper right corner, click on 'Profile'.

# Your Discogs username is the last component of the profile URL. IF you do

# not have a Discogs account, leave blank.

DISCOGS_USER="my username"

# The Discogs API token can be found by visiting

# https://www.discogs.com/settings/developers

DISCOGS_TOKEN="my token found in https://www.discogs.com/settings/developers" 
```

- tar.gz is "unzipped" in `/Users/me/Documents`
- Obsidian Vault is opened and plugins updated
- open `/Users/me/Documents/Obsidian-Custom-Discogs-1.0.2r6` in terminal
	- Run `setup`
		- tested on both `./setup -u myusername -t mytoken` and `./setup`
	- Script starts runs and this text appears


```
me@me Obsidian-Custom-Discogs-1.0.2r6 % ./setup -u myusername -t mytoken

Generating markdown for all items in Discogs user myusername collection

API token in use, requests will be faster and images downloaded

Please be patient. A large Discogs collection may take a while.

  

Release page 1/19 ..............

```

- After the 19 pages are "finished" generating markdown this comes up

```
Generating markdown for all artists

API token in use, requests will be faster and images downloaded

Please be patient. A large Discogs collection or library may take a while.

Creating artist markdown for 24-7_Spyz

Creating artist markdown for Abacus

Creating artist markdown for Abacush

Creating artist markdown for Acker_Bilk

Creating artist markdown for Aco_Simonovski
```

- Script runs through all the artists and generates markdown files

- Script generates the folder `Discogs`
	- Location is `/Users/me/Documents/Obsidian-Custom-Discogs-1.0.2r6/Discogs`
	- Here subfolders are generated named by artist
	- in each subfolder are markdown files for the releases for the artist
	- Release markdown files are generated
	- Artist markdown files are generated
	- No images for releases or artist are present
- The `/Users/me/Documents/Obsidian-Custom-Discogs-1.0.2r6/assets/albumcovers` is generated but no images are imported into it.
- in the folder `/Users/jonasd.jensen/Documents/Obsidian-Custom-Discogs-1.0.2r6/Tools/Discogs/json` I see: 
	- a large amount of folders with a naming scheme of numbers
	- a folder named `artists`
	- a folder named `releases_myusername`
- all these folders contain json files where I can see that the json files contain urls to discogs with the images that I expected to be dowloaded and visible in the vault.


For me it seems like the issue is located somewhere in the area where the magic in taking the urls and downloading them and placing them in the correct md files should happen. I might be mistaken but that is my best guess.

**Comment by doctorfree** [comment]
@Hejjeghedderfuglekigger let's start by examining the contents of your `~/.config/mpprc` file. You write:

```
The Discogs username can be found by visiting discogs.com. Login, use the
# dropdown of your user icon in the upper right corner, click on 'Profile'.
# Your Discogs username is the last component of the profile URL. IF you do
# not have a Discogs account, leave blank.
DISCOGS_USER="my username"
# The Discogs API token can be found by visiting
# https://www.discogs.com/settings/developers
DISCOGS_TOKEN="my token found in https://www.discogs.com/settings/developers" 
```

The `DISCOGS_USER` should be your registered username on discogs.com and DISCOGS_TOKEN should be the API token for that account. Do you have an account on discogs.com and is that reflected correctly in `mpprc` ? That is, are you using `my username` and `my token ...` as placeholders in your report for the actual username and token?

It is correct to not supply your credentials/token in an issue report publicly accessible. I just want to verify that your `mpprc` is setup correctly. If so then the setup process should have created the file `<username>_Discogs_User_Profile.md` in the top level of your vault. What does the following command return:

```bash
ls /Users/jonasd.jensen/Documents/Obsidian-Custom-Discogs-1.0.2r6/*User*.md
```

Once we verify your `mpprc` is setup correctly we can dig deeper.

**Comment by Jonasdj95** [comment]
it is just placeholders to not have it publicly accessible. I have a user on discogs and I have found, copied and pasted the token at the designated location in the mpprc-file

the returned value is

/Users/jonasd.jensen/Documents/Obsidian-Custom-Discogs-1.0.2r6/myusername_Discogs_User_Profile.md

**Comment by doctorfree** [comment]
@Hejjeghedderfuglekigger thanks for verifying that for me. After examining the download scripts I found another dependency that may be missing on your system. The cover art downloads use `wget` but then if the image file is not in PNG format `convert` from ImageMagick is used to convert to PNG. I may not have documented this so it may be the case that cover art downloads are failing because `convert` is not found.

Can you check for the existence of the `convert` utility on your system? It can be installed with Homebrew with `brew install imagemagick`. I am not familiar with the Pop OS package manager or repositories but ImageMagick can usually be installed on Linux systems with the native package manager, e.g. on Ubuntu `sudo apt install imagemagick`.

If this is the issue, ImageMagick not installed, then try again (sorry!) and let me know. If not I will keep digging. I ned to document this dependency.

**Comment by Jonasdj95** [comment]
I did not have imagemagick. I will install it now, try the proces again and then get back to you with the results

**Comment by Jonasdj95** [comment]
Imagemagick did the trick. after installing it the images were downloaded everything seems to be as it should

Thank you for helping. I really appreciate it

**Comment by doctorfree** [comment]
Great. Thanks for working with me on this. As a result of this issue a bug was fixed and a dependency discovered. Good work!
